package com.baseballanalysis.utils;

public class Queries {
	public static String teamPerformance = "select yearid,lgid,teamid,name,G,W,L,R,AB,H,HR,SO,CS,RA,ER,CG,SHO,HA,HRA,FP,attendance,SOA,RANK from teams where yearid>=%s and yearid<=%s and ('%s' like CONCAT(CONCAT('%%',teamid),'%%')) order by yearid";
	public static String playerSalary = "select m.namegiven,sum(s.salary) from \"Salaries\" s, master m where s.playerid = m.playerid and yearid>=%s and yearid<=%s and ('%s' like CONCAT(CONCAT('%%',teamid),'%%')) group by s.playerid,m.namegiven";
	public static String teamOrientationBattingPitching = "select batting.teamid,battingRank,pitchingRank,runs,outs from (select runs,battingRank, teamid from (select runs,rownum as battingRank, teamid from (select sum(t.R) as runs, t.teamid from teams t where t.yearid>=%s and t.yearid<=%s group by t.teamid order by runs desc)) where"
			+ "('%s' like CONCAT(CONCAT('%%',teamid),'%%'))) batting,"
			+ "(select outs,pitchingRank, teamid from (select outs,rownum as pitchingRank, teamid from (select sum(t.SOA) as outs, t.teamid from teams t where t.yearid>=%s and t.yearid<=%s group by t.teamid order by outs desc)) where"
			+ "('%s' like CONCAT(CONCAT('%%',teamid),'%%'))) pitching where batting.teamid = pitching.teamid";

	public static String teamTendency = "select playerid, CONCAT(namefirst,CONCAT(' ',namelast)), bats, throws from master where playerid in"
			+ "(select distinct playerid from appearances where yearid>=%s and yearid<=%s and ('%s' like CONCAT(CONCAT('%%',teamid),'%%')))";

	public static String playerBirthCountry = "select birthcountry, count(playerid) from master where playerid in(select distinct playerid from appearances where yearid>=%s and yearid<=%s and ('%s' like CONCAT(CONCAT('%%',teamid),'%%'))) group by BIRTHCOUNTRY";
	public static String playerBirthState = "select CONCAT('US-',birthstate), count(playerid) from master where playerid in(select distinct playerid from appearances where yearid>=%s and yearid<=%s and ('%s' like CONCAT(CONCAT('%%',teamid),'%%'))) group by CONCAT('US-',birthstate)";
	public static String playerBirthCity = "select birthcity, count(playerid) from master where playerid in(select distinct playerid from appearances where yearid>=%s and yearid<=%s and ('%s' like CONCAT(CONCAT('%%',teamid),'%%'))) group by birthcity";
	public static String allManagers = "select distinct managers.playerid, CONCAT(namefirst,CONCAT(' ',namelast)) from managers ,master where managers.playerid = master.playerid;";
	public static String searchPlayer = "select playerid, CONCAT(namefirst,CONCAT(' ',namelast)) as name from master where playerid in (select distinct playerid from appearances where yearid>=%s and yearid<=%s) and (LOWER(namefirst) like LOWER('%%%s%%') or LOWER(namelast) like LOWER('%%%s%%')) and ROWNUM < 100";
	public static String playerSalariesOverTheYears = "select yearid,teamid, playerid, salary from \"Salaries\" where playerid = '%s' and yearid >= %s and yearid <=%s order by yearid";
	public static String playersWithWeightGroups = "select CONCAT((CAST(m.weight/10 as integer)*10 - 5),CONCAT('-',(CAST(m.weight/10 as integer)*10 + 5))) as weightGroup, count(distinct b.playerid) from batting b,master m where b.playerid = m.playerid and b.yearid>=%s and b.yearid<=%s and ('%s' like CONCAT(CONCAT('%%',b.teamid),'%%')) group by CAST(m.weight/10 as integer)";
	public static String playersWithHeightGroups = "select CONCAT((CAST(m.height/2 as integer)*2 - 1),CONCAT('-',(CAST(m.height/2 as integer)*2))) as heightGroup, count(distinct b.playerid) from batting b,master m where b.playerid = m.playerid and b.yearid>=%s and b.yearid<=%s and ('%s' like CONCAT(CONCAT('%%',b.teamid),'%%')) group by CAST(m.height/2 as integer)";
	public static String battingWeightGroups = "select CONCAT((CAST(m.weight/10 as integer)*10 - 5),CONCAT('-',(CAST(m.weight/10 as integer)*10 + 5))) as weightGroup, count(distinct b.playerid)as Num_of_Players, Sum(b.R), Sum(b.HR)  from batting b, master m where b.playerid = m.playerid and b.yearid>=%s and b.yearid<=%s and ('%s' like CONCAT(CONCAT('%%',b.teamid),'%%')) group by CAST(m.weight/10 as integer)";
	public static String battingHeightGroups = "select CONCAT((CAST(m.height/2 as integer)*2 - 1),CONCAT('-',(CAST(m.height/2 as integer)*2))) as heightGroup, count(distinct b.playerid)as Num_of_Players, Sum(b.R), Sum(b.HR)  from batting b, master m where b.playerid = m.playerid and b.yearid>=%s and b.yearid<=%s and ('%s' like CONCAT(CONCAT('%%',b.teamid),'%%')) group by CAST(m.height/2 as integer)";
	public static String pitchingWeightGroups = "select CONCAT((CAST(m.weight/10 as integer)*10 - 5),CONCAT('-',(CAST(m.weight/10 as integer)*10 + 5))) as weightGroup, count(distinct p.playerid)as Num_of_Players, Sum(p.SO), Sum(p.SHO)  from pitching p, master m where p.playerid = m.playerid and p.yearid>=2010 and p.yearid<=2014 and ('CHA' like CONCAT(CONCAT('%',p.teamid),'%')) group by CAST(m.weight/10 as integer)";
	public static String pitchingHeightGroups = "select CONCAT((CAST(m.height/2 as integer)*2 - 1),CONCAT('-',(CAST(m.height/2 as integer)*2))) as heightGroup, count(distinct p.playerid)as Num_of_Players, Sum(p.SO), Sum(p.SHO)  from pitching p, master m where p.playerid = m.playerid and p.yearid>=2010 and p.yearid<=2014 and ('CHA' like CONCAT(CONCAT('%',p.teamid),'%')) group by CAST(m.height/2 as integer)";
	public static String records[] = new String[] {
			"Select CONCAT('Most runs ever scored by any player is <b>',CONCAT(Total_runs,CONCAT('</b>, scored by <b>',CONCAT(Namegiven,'</b>.')))) from (Select Master.Namegiven, TR.Total_runs from Master, (Select PlayerID, sum(NVL(R,0))as Total_Runs from Batting group by PlayerID) TR where Master.PlayerID = TR.PlayerID order by TR.Total_runs DESC) where ROWNUM = 1",
			"Select CONCAT('<b>',CONCAT(Namegiven,CONCAT('</b> ',CONCAT('has the record of highest Strikeouts in the history of game with total of <b>',CONCAT(Total_outs,'</b>.'))))) from (Select Master.Namegiven, TOuts.Total_outs from Master, (Select PlayerID, sum(NVL(SO,0))as Total_Outs from Pitching group by PlayerID) TOuts where Master.PlayerID = TOuts.PlayerID order by TOuts.Total_outs DESC) where ROWNUM = 1",
			"Select CONCAT('Youngest person ever to manage a team is <b>',CONCAT(Namegiven,CONCAT('</b>, He was <b>',CONCAT(Age,' </b> at the time.')))) from ( Select M.Namegiven, A.Debut-M.Birthyear as Age from Master M, (Select PlayerID, min(YearID) as Debut from Managers where PLYRMGR = 'N'  group by PlayerID) A where A.PlayerId = M.PlayerID order by Age) where ROWNUM =1",
			"select CONCAT('<b>',CONCAT(m.Namegiven,CONCAT('</b>',CONCAT(' has the received the highest salary ever in <b>',CONCAT(s.yearid,CONCAT('</b>, which was <b>$',CONCAT(s.salary,'</b>.'))))))) from \"Salaries\" s,APPEARANCES a,master m where a.playerid = m.playerid and a.playerid = s.playerid and salary >= all(select salary from \"Salaries\") and ROWNUM = 1" };
}
